### PR TITLE
fix `valueOf` to automatically return based on dtype

### LINKED ISSUE #86: `valueOf()` boolean Tensors causes bun to crash
Minimal example:

```
const s = sm.scalar(7).isinf()
console.log(s.dtype, s.shape)
console.log(s.valueOf())
```

Output is as follows:
```
3 []

uh-oh: A C++ exception occurred
bun will crash now 😭😭😭

----- bun meta -----
Bun v0.1.13 (55bdf268) macOS Silicon 21.6.0
AutoCommand: 
Elapsed: 91ms | User: 84ms | Sys: 14ms
RSS: 84.13MB | Peak: 84.13MB | Commit: 67.11MB | Faults: 0
----- bun meta -----

Crash report saved to:
  ~/.bun/.bun-crash/v0.1.13-1666604912355.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

libc++abi: terminate_handler unexpectedly returned
```

### PR DESCRIPTION
**Pull request by cryptodeal**
Update `valueOf` to automatically handle returning the correct type for JS runtime using switch case on `dtype`. Add native code to handle scalar values. Fixes #86

### CODE REVIEW

File: shumai/cpp/flashlight_binding.cc [hunk 1]
```diff
@@ -534,12 +546,66 @@ unsigned* _uint64Buffer(void* t) {
   }
 }
 
-float _scalar(void* t) {
+float _float32Scalar(void* t) {
+  LOCK_GUARD
+  auto* tensor = reinterpret_cast<fl::Tensor*>(t);
+  return tensor->scalar<float>();
```
Comment (bwasti) [inline shumai/cpp/flashlight_binding.cc:552]: I think we'll want `asScalar` here (which implicitly casts to the type without throwing)

https://fl.readthedocs.io/en/latest/tensor.html?highlight=scalar#_CPPv4I0ENK2fl6Tensor8asScalarE1Tv

**Review by bwasti — COMMENTED** [review]
woo!  small change to prevent exceptions on type mismatch
